# Generated by Django 2.1 on 2019-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190102_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_account_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_account_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
